### PR TITLE
Bugfix skipped subshops in 6.2 do not work

### PR DESCRIPTION
**Pull request by alfredbez**
I faced this issue today:

image

We're using an EE 6.2-rc with two shops with ids 1 and 6. Shop-ID 1 works as expected, but shop-ID 6 throws this error. After adding the line from cf281a4af64085ff8fc7bda7804fbe31ee374960 it worked.

I fixed some code style violations and a typo in a comment alongside. I have no idea how to reproduce the behavior at the moment, it's also hard to write a test for this since this is a EE feature and I guess we will get some sort of license/auth problems. If we find a way to solve the license problem I can try to add a test case for this. I have already some EE related integration tests with multiple shops in private projects.

### CODE REVIEW

**Comment by keywan-ghadami-oxid** [comment]
@alfredbez was this already tested with oxid 6.1, or should I test it with a oxid 6.1?

**Comment by alfredbez** [comment]
Not tested it yet with 6.1, but I can do it in the next week. I also have an idea about integration tests with EE, let's talk about this next week, if you find some time. If you wish I can also just prepare a branch and show you the idea.

**Comment by alfredbez** [comment]
@shahid-oxid just stumbled upon the same issue in another project (OXID Compilation Version 6.1.5 / `oxid-esales/oxideshop-ce`  `v6.3.6`) and this patch made it work for him, too.

**Comment by alfredbez** [comment]
@mnarkevicius reported the same problem today, the fix did solve the problem for him, too. We're using OXID 6.1 in this project, so I will merge this and create a new release.

**Pull request merged**
