### PR TITLE
feature: add shop parameter

### PR DESCRIPTION
**Pull request by alfredbez**
Works like this:
```
vagrant@oxid-vm:~$ php /var/www/shop/vendor/bin/oxid config:import --shop=1 | grep 'Importing config for shop'
Importing config for shop 1
vagrant@oxid-vm:~$ php /var/www/shop/vendor/bin/oxid config:import --shop=1,3,5 | grep 'Importing config for shop'
Importing config for shop 1
Importing config for shop 3
Importing config for shop 5
vagrant@oxid-vm:~$ php /var/www/shop/vendor/bin/oxid config:import | grep 'Importing config for shop'
Importing config for shop 1
Importing config for shop 2
Importing config for shop 3
Importing config for shop 4
Importing config for shop 5
Importing config for shop 6
Importing config for shop 7
Importing config for shop 8
Importing config for shop 9
Importing config for shop 10
Importing config for shop 11
Importing config for shop 12
Importing config for shop 13
Importing config for shop 14
Importing config for shop 15
Importing config for shop 16
Importing config for shop 17
Importing config for shop 18
Importing config for shop 19
Importing config for shop 20
Importing config for shop 21
Importing config for shop 22
Importing config for shop 23
Importing config for shop 24
Importing config for shop 25
Importing config for shop 26
Importing config for shop 27
Importing config for shop 28
Importing config for shop 29
Importing config for shop 30
Importing config for shop 31
Importing config for shop 32
Importing config for shop 33
Importing config for shop 34
Importing config for shop 35
Importing config for shop 36
Importing config for shop 37
Importing config for shop 38
Importing config for shop 39
vagrant@oxid-vm:~
```

### CODE REVIEW

**Comment by keywan-ghadami-oxid** [comment]
very good, would be cool if someone(maybe me if I find time) can double check if that functionality is compatible with oxrun, oxid console and oxid core console, because they have different sub shop handling capabilities built in.

**Comment by alfredbez** [comment]
I can rebase this if we are still interested in this, otherwise we should just close this. Not sure if compatibility should be such a blocker.

**Comment by keywan-ghadami-oxid** [comment]
@alfredbez the shop option is within the oxid console already defined so it can be removed from your change, can't it?

**Comment by alfredbez** [comment]
@keywan-ghadami-oxid done

**Pull request merged**
